name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: tuacr.azurecr.io
        username: mariana
        password: v+OQC0+LkSNqmCwip/Ip6PAxQc8So7elctxsbYz4PM+ACRBa/b7Y

    - name: Build and Push Docker image
      run: |
        docker build -t tuacr.azurecr.io/flask-backend:latest .
        docker push tuacr.azurecr.io/flask-backend:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: flask-webapp
        images: tuacr.azurecr.io/flask-backend:latest
